services:
  web:
    build: ./backend
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    ports:
      - "5000:5000"
    depends_on:
      - database
    volumes:
      - ./backend/init.sql:/docker-entrypoint-initdb.d/init.sql

  ui:
    build: ./frontend
    ports:
      - "8081:80"
    depends_on:
      - web

  database:
    image: postgres:15
    environment:
      POSTGRES_DB: notesdb
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: secret
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5433:5432"

volumes:
  pgdata: